const types = {
  SET_ERROR: "SET_ERROR",
  SET_LOADING: "SET_LOADING",
  SET_USER_PROFILE: "SET_USER_PROFILE",

  SET_STUDENTS_LIST: "SET_STUDENTS_LIST",
  GET_STUDENTS_LIST: "GET_STUDENTS_LIST"
};

export default types;
