const types = {
  SET_ERROR: "SET_ERROR",
  SET_LOADING: "SET_LOADING",

  SET_SORT_GOODS: "SET_SORT_GOODS",
  SET_GOODS_LIST: "SET_GOODS_LIST",
  SET_ORDERS: "SET_ORDERS",
  SET_OPEN_MODAL_STATUS: "SET_OPEN_MODAL_STATUS",
  SET_ADMIN_ORDERS: "SET_ADMIN_ORDERS"
};

export default types;
